#!/bin/bash
export SRC_DIR=$(cd $1; pwd)
export DST_DIR=$(cd $2; pwd)

# echo $SRC_DIR
# echo $DST_DIR

echo '---------'
echo 'Starting search for files...'
echo '---------'
# find $SRC_DIR -name '0-absolute.c' \
#     -type f ! -path $DST_DIR/* -exec echo {} $DST_DIR \;
find $SRC_DIR -name '0-absolute.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 1/23'
find $SRC_DIR -name '0-contact_strings.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 2/23'
find $SRC_DIR -name '0-first_digit.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 3/23'
find $SRC_DIR -name '0-lowercase.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 4/23'
find $SRC_DIR -name '5-print_number.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 5/23'
find $SRC_DIR -name '0-uppercase_string.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 6/23'
find $SRC_DIR -name '1-cap_string.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 7/23'
find $SRC_DIR -name '1-nconcat_strings.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 8/23'
find $SRC_DIR -name '1-power.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 9/23'
find $SRC_DIR -name '1-swap_int.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 10/23'
find $SRC_DIR -name '1-uppercase.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 11/23'
find $SRC_DIR -name '2-print_array.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 12/23'
find $SRC_DIR -name '2-square_root.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 13/23'
find $SRC_DIR -name '2-str_len.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 14/23'
find $SRC_DIR -name '2-string_copy.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 15/23'
find $SRC_DIR -name '3-is_prime_number.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 16/23'
find $SRC_DIR -name '3-print_string.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 17/23'
find $SRC_DIR -name '3-string_ncopy.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 18/23'
find $SRC_DIR -name '4-positive_or_not.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 19/23'
find $SRC_DIR -name '4-reverse_string.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 20/23'
find $SRC_DIR -name '4-strings_compare.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 21/23'
find $SRC_DIR -name '5-reverse_array.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 22/23'
find $SRC_DIR -name '5-string_to_integer.c' \
    -type f ! -path "$DST_DIR/*" -exec cp {} $2 \;
echo 'Done: 23/23'
echo '---------'
echo 'All Done!'
echo '---------'
