CC=gcc
CFLAGS=-Wall -Werror -Wextra -pedantic -g
SOURCES=0-main ntree_insert
OBJECTS=free_str_array.o  ntree_free.o  ntree_print.o  string_split.o

all: 0-main

0-main: $(SOURCES).c $(OBJECTS)

run:
	./0-main

clean:
	rm 0-main
