CC=gcc
CFLAGS=-Wall -Werror -Wextra -pedantic

all: test_double_pointer test_int_size

test_double_pointer: test_double_pointer.c

test_int_size: test_int_size.c

.PHONY: clean
clean:
	$(RM) test_double_pointer test_int_size
